from pathlib import Path
import json,csv,zipfile,html
R=Path(__file__).resolve().parents[1];D=R/'dist'; data=json.loads((D/'data/site-data.json').read_text());sources=data['sources']
base=(D/'index.html').read_text();head=base.split('<main id="main">')[0];foot=base.split('</main>')[1].split('<script')[0]
def page(name,title,body):
 (D/name).write_text(head.replace('Beyond Sedona — A seasonal tourism field guide',title+' — Beyond Sedona').replace('href="#explore"','href="index.html#explore"').replace('href="#recommendations"','href="index.html#recommendations"')+'<main id="main" class="document">'+body+'</main>'+foot+'</body></html>')
def link(url,text):return f'<a href="{url}" target="_blank" rel="noopener">{text} ↗</a>'
method_sections=[
('Purpose and scope','Help Arizona tourism planners screen seasonal side trips from Sedona. Six selected state parks represent two Sedona-area reference sites and four candidates in Cottonwood, Jerome and Camp Verde. These are attraction comparisons, not measurements of total municipal tourism.'),
('Collection and provenance','Public secondary research was checked on September 22, 2026 (UTC). The dataset contains 144 monthly park observations for 2024–2025, 54 spending entries, three resident-response percentages, six hotel-market observations, and a destination evidence register. The 2024 attendance PDF was downloaded and extracted; 2025 counts were transcribed from the indexed NAU report after its direct download returned 404. Monthly sums match each published annual total; the six 2025 totals also match the university economic study. No personal records were collected.'),
('Sources and definitions','Attendance: Arizona State Parks, compiled by NAU [1–2]. A visit is not a unique person; counts include local users. Spending: University of Arizona [3], 2025 nominal dollars associated with non-local visitors within 50 miles of each park, Tables 35 and 44. Use the published direct totals; category sums may differ slightly through rounding. Resident views: Sedona’s weighted 2024 probability-sample survey [4], 551 respondents overall, 20% response rate and reported overall ±4 percentage-point margin at 95% confidence. Hotel context: City of Sedona / STR [5], August–October 2025, Sedona+ and Village of Oak Creek+ study areas.'),
('Calculations and interpretation','Peak-relative visitation = month visits ÷ the park’s largest monthly count × 100. Annual share = month visits ÷ annual visits × 100. Year-over-year change = (2025 total ÷ 2024 total − 1) × 100. Summer means June–August. Rockin’ River Ranch’s January 2024 zero is marked not yet open and excluded from the comparable five-park change. No weighted opportunity score or spending forecast is used. Proposed pilots combine observed timing with attraction type and documented access.'),
('Limits and next evidence','Two years cannot establish a long-term trend or explain changes. Counts are not adjusted for open days, weather, closures, or events. Spending areas overlap and do not establish town receipts or campaign impact. Survey nonresponse and coverage bias remain; Sedona views do not represent receiving communities. Hotel reporting samples and geography differ, and a closure affected supply. Neighboring-town room availability, carrying capacity, travel times, and resident consent are unverified. A pilot should establish these conditions and measure whether side trips replace time in Sedona or extend a trip.')]
method_html=''.join(f'<h2>{h}</h2><p>{p}</p>' for h,p in method_sections)
refs=[('1','NAU attendance 2024',sources['vis2024']),('2','NAU attendance 2025',sources['vis2025']),('3','University of Arizona park economics, 2025',sources['economics']),('4','Sedona National Community Survey, 2024',sources['residents']),('5','Sedona lodging report, October 2025',sources['lodging'])]
page('methodology.html','One-page methodology','<p class="eyebrow">DATA & METHODOLOGY NOTE</p><h1>How this study works.</h1><p><a class="button" href="data/methodology.pdf" download>Download the one-page PDF ↓</a></p>'+method_html+'<h2>Primary sources</h2><ol>'+''.join(f'<li>{link(u,t)}</li>' for _,t,u in refs)+'</ol><p><a href="methods.html">Full source register and data dictionary ↗</a></p>')
(R/'research/methodology-content.json').write_text(json.dumps({'sections':method_sections,'refs':refs}))
source_cards=f'''
<article class="source-card" id="visitation"><h3>1–2. Monthly park visitation</h3><p>Arizona State Parks Revenue and Attendance Monthly Reports, compiled by NAU’s Arizona Hospitality Research and Resource Center. Calendar years 2024 and 2025, January–December. Units: park visits. Six selected parks, 144 observations.</p><p>{link(sources['vis2024'],'2024 original PDF')} · {link(sources['vis2025'],'2025 original PDF')} · {link('https://tourism.az.gov/data-trends/','Arizona tourism report archive')}</p><p>The 2024 PDF was downloaded and parsed with text extraction. The 2025 table was available through indexed source text, but direct download returned 404 during collection. Its six annual totals were cross-checked against Table 2 of source 3. No missing month was imputed. Rockin’ River Ranch’s reported January 2024 zero is retained with a “not yet open” flag, and shown as a dash in the heatmap. The park opened in February 2024. Totals in these tables are counts of visits, not unique individuals.</p></article>
<article class="source-card" id="spending"><h3>3. Visitor spending around state parks</h3><p>Dari Duval and Claudia Montanía, University of Arizona Cooperative Extension, <em>2025 Economic Contributions & Impacts of Arizona State Parks</em>, published June 2026. Calendar year 2025; nominal USD. Tables 35 and 44 report category spending and direct totals associated with non-local visitors.</p><p>{link(sources['economics'],'Original report')} · {link('https://extension.arizona.edu/publication/2025-economic-contributions-impacts-arizona-state-parks','Publication page')}</p><p>The study uses a 2025 visitor survey (10,693 observations across 30 parks; 8,600 with usable expenditure information). Spending concerns activity in and within 50 miles of each park. Non-local means visitors from over 50 miles away. Our chart uses direct spending, not indirect or induced effects. Source category totals can differ from published direct totals by $1,000 through rounding. We do not sum parks into a regional windfall or calculate per-new-visitor revenue. Park-level sampling uncertainty is not quantified here.</p></article>
<article class="source-card" id="residents"><h3>4. Sedona resident feedback</h3><p>National Community Survey, City of Sedona, 2024. Fieldwork September 9–October 28, 2024. We use the weighted probability sample, excluding the separate open-participation results. Overall sample: 551; response rate: 20%; reported overall margin of error: up to ±4 percentage points at 95% confidence. The item-specific sample size was not separately published in the extracted table.</p><p>{link(sources['residents'],'Original survey report')} · {link('https://www.sedonaaz.gov/your-government/departments-and-programs/city-manager/citizen-engagement/citizen-surveys','City survey archive')}</p><p>Question: “In the future, how much of a role would you like to see tourism have in Sedona’s economy?” Less: 49%; same: 45%; more: 6%. Nonresponse and demographic coverage may affect estimates. These views do not measure support for side-trip promotion, and cannot be assigned to Cottonwood, Jerome or Camp Verde.</p></article>
<article class="source-card" id="lodging"><h3>5. Hotel-market context</h3><p>City of Sedona Tourism Program, October 2025 Lodging and Spending Reports, STR hotel review, PDF page 4. Six monthly observations: August–October 2025 for Sedona+ and Village of Oak Creek+. Occupancy is rooms sold / rooms available; ADR is average daily room rate in USD, not total trip cost.</p><p>{link(sources['lodging'],'Original lodging report')}</p><p>Read the October 2025 Hotel Review panel; the PDF also contains older narrative text, which is not used. The sample note (as of April 2025) lists 21 of 44 Sedona+ hotels and 6 of 14 Village of Oak Creek+ hotels reporting. A June closure for renovation reduced Sedona+ supply. These vendor-defined markets do not measure accommodation availability in our candidate towns. We omit short-term rentals because the report uses multiple geographic and vendor definitions; no values are substituted for missing candidate-town capacity.</p></article>
<article class="source-card" id="recommendations"><h3>6. Attractions, access and operating constraints</h3><p>Official park pages checked September 22, 2026. Hours describe the published current offer, not a reconstructed 2024–2025 operating history. This study does not provide live alerts or verified driving times.</p><ul><li>{link('https://azstateparks.com/dead-horse','Dead Horse Ranch')} — Cottonwood nature, camping and river setting.</li><li>{link('https://azstateparks.com/jerome','Jerome')} — Douglas Mansion museum; daily opening listed.</li><li>{link('https://azstateparks.com/fort-verde','Fort Verde')} — historic buildings, exhibitions and event calendar.</li><li>{link('https://azstateparks.com/rockin-river/','Rockin’ River Ranch')} — Friday–Sunday operation listed; last entry 4 p.m.</li><li>{link('https://arizona-content.usedirect.com/storage/Annual_Report_FY24_FINAL_4.pdf','Arizona State Parks FY2024 annual report')} — February 2024 opening of Rockin’ River Ranch.</li><li>{link('https://verdeshuttle.com/routes/verde-shuttle/','Verde Shuttle route')} — connection between central Cottonwood and Sedona, not direct park access.</li><li>{link('https://azstateparks.com/arizona-summer-vacations','Arizona State Parks summer guide')} — experience and seasonal context.</li></ul></article>
<article class="source-card"><h3>7. Photograph</h3><p>Tavasci Marsh at Tuzigoot National Monument. Credit: National Park Service, public domain. The photograph illustrates the wider region; Tuzigoot is outside this dataset.</p><p>{link('https://www.nps.gov/articles/000/sodn-tuzi-climate-monitoring-wy2024.htm','NPS source page')}</p></article>'''
limitations='''<ul><li><strong>Selection bias:</strong> six parks were chosen for proximity and comparable public reporting. Private attractions, tribal destinations and many community businesses are outside the comparison.</li><li><strong>Capacity is unknown:</strong> fewer visits do not prove empty parking, available rooms, ecological headroom or enough staff.</li><li><strong>Timing is descriptive:</strong> two years, unequal month lengths and unknown opening-day changes limit comparison. Weather, events and closures can drive observed differences.</li><li><strong>Geographies differ:</strong> park counts, 50-mile spending areas, hotel study markets and Sedona residents cannot be combined as if they described the same population.</li><li><strong>No causal claim:</strong> side trips may extend travel or shift visits without reducing Sedona crowding. Neither campaign effects nor additional spending can be predicted from these records.</li><li><strong>Receiving-community voice:</strong> no comparable local sentiment series was collected for candidate communities. Consultation is a condition of the recommendations.</li></ul>'''
page('methods.html','Sources and methodology',f'''<p class="eyebrow">RESEARCH REGISTER / CHECKED SEPTEMBER 22, 2026 UTC</p><h1>Every number has a boundary.</h1><p class="lede">Public data can support a useful shortlist. It cannot establish how many additional visitors a place should receive.</p><div class="download-grid"><a href="data/research-dataset.zip" download>All CSV data + dictionary ↓</a><a href="data/methodology.pdf" download>One-page methodology PDF ↓</a><a href="data/park-visitation.csv" download>144 monthly park observations ↓</a><a href="data/visitor-spending.csv" download>54 spending observations ↓</a><a href="data/resident-feedback.csv" download>Resident feedback ↓</a><a href="data/hotel-context.csv" download>Hotel-market context ↓</a><a href="data/destinations.csv" download>Destination evidence register ↓</a><a href="data/data-dictionary.md" download>Definitions and calculation rules ↓</a></div><h2>How the data were collected</h2><p>We extracted published aggregate tables from public agency and university reports, then normalized park names and dates into CSV files. No surveys of individuals, device records, names, contact details, or personal locations were collected. All chart values come from the downloadable data or their documented calculations.</p><p>Each park’s 12 monthly counts is checked against its annual total. Every 2025 selected-park total also matches the university economic report. The 2024 PDF was downloaded; several other reports were readable through indexed public text despite direct-download failures. Those retrieval limitations are disclosed below.</p><h2>Calculations</h2><dl><dt>Peak-relative visitation</dt><dd>100 × monthly visits / highest monthly count for that park and year. This is an index of seasonal timing, not a percentage of capacity.</dd><dt>Share of annual visits</dt><dd>100 × monthly visits / total visits for the calendar year. Summer totals cover June, July and August.</dd><dt>Year-over-year change</dt><dd>100 × (2025 total / 2024 total − 1). The five-park combined change excludes Rockin’ River Ranch, which was not open in January 2024.</dd><dt>Recommendation method</dt><dd>Editorial screening using the seasonal pattern, attraction type, published access and missing evidence. No hidden weights or numerical “opportunity score.” September Cottonwood, summer Jerome, and off-peak Fort Verde are proposed experiments, not proven optimal choices.</dd></dl><h2>Missing data, bias and uncertainty</h2>{limitations}<h2>Source register</h2>{source_cards}<p><a href="reflection.html">Read the reflection ↗</a></p>''')
reflection='''<p class="eyebrow">REFLECTION / DRAFT FOR THE STUDENT TO PERSONALIZE</p><h1>The evidence changed the question.</h1><p class="lede">A good planning tool should make it easy to see both the opportunity and the uncertainty.</p><p>The project began with the idea that a sudden visitor surge in one city could benefit neighboring communities. The selected Arizona park data did not support that starting assumption: each of the six parks recorded fewer visits in 2025 than in 2024. We therefore shifted the question toward seasonal side-trip promotion, rather than presenting a surge that the data could not establish.</p><p>The strongest evidence concerns timing. Slide Rock’s summer concentration differs from the spring pattern at Dead Horse Ranch and Jerome. This supports considering different seasonal offers, but it does not show that visitors will choose them. A person seeking swimming may have little interest in a museum, and a quieter park may have limited staffing or challenging weather.</p><p>The spending research adds an economic reason to examine regional itineraries, but the estimates cover areas within 50 miles of each park. They are not money received exclusively by the host town, and they cannot be treated as the additional revenue a marketing campaign would generate. Similarly, Sedona’s resident survey provides a reason to take local impacts seriously; it does not speak for the communities that would receive visitors.</p><p>The resulting website is a screening tool for small, measurable pilots. It can help planners explain why a destination and season deserve consideration, identify missing evidence and make the next research step concrete. It cannot establish carrying capacity, community consent, the best allocation of a marketing budget, or a causal reduction in congestion.</p><blockquote><p>Before submission, add a short account of your own role: which assumptions you revised, what you checked, and what you learned from using an agent to collect and communicate evidence.</p></blockquote><p><a href="index.html#recommendations">Return to the proposed pilots ↗</a></p>'''
page('reflection.html','Reflection',reflection)
(R/'dist/data/reflection.md').write_text('Beyond Sedona — Reflection draft\n\n'+__import__('re').sub('<[^>]+>',' ',reflection))
# Destination evidence is an explicit dataset, including unknowns.
records=[]
for p in data['parks']:
 records.append({'park_id':p['id'],'park':p['fullName'],'community':p['community'],'role':p['role'],'experience':p['type'],'official_url':p['url'],'current_hours':'Fri-Sun 09:00-17:00; last entry 16:00' if p['id']=='rockin' else 'daily 09:00-16:30; holiday exceptions' if p['id'] in ['jerome','fort'] else 'consult official page','verified_driving_minutes':'not collected','carrying_capacity':'not verified','candidate_town_hotel_capacity':'not verified','candidate_town_resident_sentiment':'not collected','retrieved_utc':'2026-09-22'})
with (D/'data/destinations.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=records[0]);w.writeheader();w.writerows(records)
dictionary='''# Beyond Sedona: dataset dictionary
Collected 2026-09-22 UTC. Public aggregate research only. No personal records.

## park-visitation.csv (144 records)
park_id: stable key; park/community: named park and associated community (not the geography of a total visitor census); year/month: calendar period; visits: reported count of park visits, not unique people; unit: park visits; status: reported or not yet open; source_url: original report; retrieved_utc: research date. January 2024 Rockin River Ranch is zero in the source and flagged not yet open. Heatmap displays a dash. Monthly totals match annual totals. The 2025 source was accessed as indexed text because its direct download returned 404. The 2024 file was downloaded and text-extracted.

## visitor-spending.csv (54 records)
park_id/park: attraction associated with the spending; year: 2025; category: one of eight expenditure categories or Published direct total; value_usd: nominal dollars, rounded by source; geography: within 50 miles of park; population: non-local visitors from over 50 miles away; source_table: Table 35 or 44 of University of Arizona report. These overlapping areas are not town boundaries. Category sums can differ slightly from published totals due to rounding. Do not sum Published direct total alongside its categories. No park totals are added into a regional forecast. The report's multi-park survey includes 10,693 responses, 8,600 with usable expenditure data; park-level uncertainty is not estimated here.

## resident-feedback.csv (3 records)
Weighted 2024 City of Sedona probability sample. response: preferred tourism role in economy; percent: weighted percent; overall_sample_n: 551 respondents to survey overall, NOT the item denominator; item_sample_n: not separately reported; overall_response_rate_pct: 20; overall_margin_error_pp: 4 at 95% confidence. Separate open-participation data excluded. No inference to receiving communities. Nonresponse and coverage bias remain.

## hotel-context.csv (6 records)
study_area: STR's Sedona+ or Village of Oak Creek+ market; year/month: August-October 2025; occupancy_pct: rooms sold / rooms available x 100; adr_usd: average daily room rate in dollars, rounded in source; source_page: PDF page 4. Not destination-town availability. The source's current hotel table is used rather than older narrative text embedded in its PDF. A June renovation closure reduced Sedona+ supply. No short-term rental metrics included. The report's April 2025 sample note lists 21/44 Sedona+ hotels and 6/14 Village of Oak Creek+ hotels reporting.

## destinations.csv (6 records)
Park names, associated communities, reference/candidate role, experience, official links, published current hours where verified, and explicit missingness. Hours were checked in September 2026; these are not 2024/25 operating-day histories. Driving times, capacity and receiving-community attitudes are unverified, never encoded as zero.

## Derived values
Peak-relative index = 100 * monthly visits / maximum monthly visits for that park-year.
Annual share = 100 * monthly visits / sum of 12 monthly visits.
YOY percent = 100 * (2025 total / 2024 total - 1).
Summer = June-August. No statistical significance is claimed for count changes.
Five-park combined change excludes Rockin River Ranch because it opened February 2024.
Recommendations are qualitative screening judgments with explicit prerequisites; not an optimized score.

## Scope and reproducibility
Two years cannot establish long-term trends. Counts are not normalized for opening days, weather or closures. Park visits may include local users and repeated visits. Detailed collection and source notes are on methods.html; the source repository includes scripts/prepare_data.py and the 2024 extracted source. The 2025 transcribed fixture is in that script. Run python3 scripts/prepare_data.py to regenerate quantitative CSVs. scripts/build_documents.py writes destination data and methodology content. No runtime API key or third-party analytics is used.
'''
(D/'data/data-dictionary.md').write_text(dictionary)
with (D/'data/source-register.csv').open('w',newline='') as f:
 w=csv.writer(f);w.writerow(['source_id','title','url','retrieved_utc']);w.writerows((i,t,u,'2026-09-22') for i,t,u in refs)
print('Created methodology, sources, reflection, destination CSV and dictionary')
